import TQueryProvider from '@/TQueryProvider'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Noto_Sans_KR } from 'next/font/google'
import '../styles/global.css'
import PrivateRouter from '@/hoc/privateRoute'

const notoSansKR = Noto_Sans_KR({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const client = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <TQueryProvider>
        <body className={notoSansKR.className}>{children}</body>
      </TQueryProvider>
    </html>
  )
}
