import TQueryProvider from '@/TQueryProvider'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import '../styles/global.css'
import { Toaster } from 'react-hot-toast'

const notoSansKR = Noto_Sans_KR({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <TQueryProvider>
        <body className={notoSansKR.className}>
          {children}
          <Toaster />
        </body>
      </TQueryProvider>
    </html>
  )
}
